"""empty message

Revision ID: b3974c3e47d4
Revises: 74726003b49d
Create Date: 2021-05-28 11:14:42.423923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3974c3e47d4'
down_revision = '74726003b49d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_recovery_request',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('expire_at', sa.Integer(), nullable=False),
    sa.Column('change_made', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_password_recovery_request_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_recovery_request'))
    )
    op.drop_table('recover_password_request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recover_password_request',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('expire_at', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('change_made', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_recover_password_request_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_recover_password_request')
    )
    op.drop_table('password_recovery_request')
    # ### end Alembic commands ###
